### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [JoseAntonioLattice/libgnuplot-fortran#1]
I suggest adding the topics `plot`, `plotting`, `gnuplot`, `fortran` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by JoseAntonioLattice** [comment]
Dear Beliavsky, thanks for your suggestions. I agree with all of them. I have already make the changes to the topics. 
Thanks for stoping by.

Regards

Antonio
